<?php

/**
 * @file
 * Contains chajchu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\block\Entity\Block;
use Drupal\Core\Session\AccountInterface;


/**
 * Implements hook_help().
 */
function chajchu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chajchu module.
    case 'help.page.chajchu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The chajchu functionalty module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chajchu_theme() {
  $theme = [];

  return $theme;
}

/**
 *  Implements hook_page_attachments().
 */
function chajchu_page_attachments(array &$page) {
  $description = [
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'description',
      'content' => t('Searcher of products and services'),
    ],
  ];
  $keywords = [
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'keywords',
      'content' => t('Products, services in general. Like garden services, mason, colourman, secreatary, doctor, computing, companies, etc'),
    ],
  ];

  $page['#attached']['html_head'][] = [
    $description,
    'description',
  ];

  $page['#attached']['html_head'][] = [
    $keywords,
    'keywords',
  ];


}

