<?php

/**
 * @file
 * Contains chajchu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\block\Entity\Block;
use Drupal\Core\Session\AccountInterface;


/**
 * Implements hook_help().
 */
function chajchu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chajchu module.
    case 'help.page.chajchu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The chajchu functionalty module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chajchu_theme() {
  $theme = [];

  return $theme;
}


/**
 * Implements hook_block_access().
 */
/*
function chajchu_block_access(Block $block, $operation, AccountInterface $account, $langcode) {

  //print_r($block->getPluginId());
  //print_r("<br>");
  
  if($block->getPluginId() == "system_menu_block:account") {
    $block->setRegion('sidebar_second');
    $block->setWeight('2');
    $block->save();
  }

  if($block->getPluginId() == "system_menu_block:main") {
    $block->disable();
    $block->save();
  }

  if($block->getPluginId() == "system_breadcrumb_block") {
    $block->disable();
    $block->save();
  }

  if($block->getPluginId() == "help_block") {
    $block->disable();
    $block->save();
  }

  if($block->getPluginId() == "user_login_block") {
    $block->disable();
    $block->save();
  }

  if($block->getPluginId() == "search_form_block") {
    $block->disable();
    $block->save();
  }
  
  if($block->getPluginId() == "system_menu_block:tools") {
    $block->disable();
    $block->save();
  }
  
  if($block->getPluginId() == "system_menu_block:footer") {
    $block->disable();
    $block->save();
  }

  return;
}*/